# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multi_greeter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "hellostreamingworld.HelloRequest" do
    optional :name, :string, 1
    optional :num_greetings, :string, 2
  end
  add_message "hellostreamingworld.HelloReply" do
    optional :message, :string, 1
  end
end

module Hellostreamingworld
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("hellostreamingworld.HelloRequest").msgclass
  HelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("hellostreamingworld.HelloReply").msgclass
end
