# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "test_app.HelloRequest" do
    optional :name, :string, 1
  end
  add_message "test_app.HelloReply" do
    optional :message, :string, 1
  end
end

module TestApp
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("test_app.HelloRequest").msgclass
  HelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("test_app.HelloReply").msgclass
end
